output "instance_ip_addr" {
  value       = aws_instance.ec2
  description = "The public IP address of the main server instance."
}

output "ssh_key" {
  value       = tls_private_key.ssh.private_key_pem
  description = "ssh key generated by terraform"
  sensitive = true
}
